version: '3.8'
name: docker-hugo
services:
  hugo:
    container_name: hugo-dev
    build: .
    ports:
      - "1313:1313"
    volumes:
      - .:/src
      - /src/node_modules
      - /src/public
      - /src/resources
    environment:
      - HUGO_REFRESH_TIME=1
      - HUGO_THEME=PaperMod
      - HUGO_BASEURL=http://localhost:1313/
    command: hugo server --bind 0.0.0.0 --buildDrafts --buildFuture --disableFastRender
    stdin_open: true
    tty: true
